spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbx #本地
    #url: jdbc:mysql://47.115.226.106:3306/dbx #云
    username: root
    password: yiti241325


# mp日志
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
      banner: off # 关闭mybatisplus启动图标

server:
  servlet:
    session:
      timeout: 1800
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8010


